### ISSUE TITLE
Can't find init generator

### ISSUE THREAD

**Issue by BleedingDev** [gperdomor/nx-tools#1065]
I wanted to use `nx-container`, but it refuses even the first step of initialisation. What am I doing wrong?

```powershell
nx g @nx-tools/nx-container:init coursition  --verbose     
[0.00ms] ".env.local"
[0.00ms] ".env.local"

 NX   Unable to resolve @nx-tools/nx-container:init.

Cannot find generator 'init' in D:\Side\nmit-coursition\node_modules\@nx-tools\nx-container\generators.json.

Error: Unable to resolve @nx-tools/nx-container:init.
Cannot find generator 'init' in D:\Side\nmit-coursition\node_modules\@nx-tools\nx-container\generators.json.
    at getGeneratorInformation (D:\Side\nmit-coursition\node_modules\nx\src\command-line\generate\generator-utils.js:39:15)
    at D:\Side\nmit-coursition\node_modules\nx\src\command-line\generate\generate.js:218:248
    at async handleErrors (D:\Side\nmit-coursition\node_modules\nx\src\utils\params.js:9:24)
    at async Object.handler (D:\Side\nmit-coursition\node_modules\nx\src\command-line\generate\command-object.js:13:22)

nmit-coursition  switch-to-bun-package-manager via 🍞 v1.1.13  v20.14.0  took 12s
❯ nx report
[0.00ms] ".env.local"
[0.00ms] ".env.local"
[0.00ms] ".env.local"
[0.00ms] ".env.local"

 NX   Report complete - copy this into the issue template

Node   : 20.14.0
OS     : win32-x64
bun    : 1.1.13

nx (global)        : 19.0.7
nx                 : 19.2.0
@nx/js             : 19.2.0
@nx/linter         : 19.2.0
@nx/eslint         : 19.2.0
@nx/workspace      : 19.2.0
@nx/devkit         : 19.2.0
@nx/eslint-plugin  : 19.2.0
@nx/next           : 19.2.0
@nx/playwright     : 19.2.0
@nx/react          : 19.2.0
@nrwl/tao          : 19.2.0
@nx/web            : 19.2.0
@nx/webpack        : 19.2.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/next/plugin
@nx/eslint/plugin
---------------------------------------
Community plugins:
@nx-extend/shadcn-ui   : 2.0.2
@nx-tools/nx-container : 6.0.1


nmit-coursition  switch-to-bun-package-manager via 🍞 v1.1.13  v20.14.0  took 4s
```

**Comment by gperdomor** [comment]
Hi @BleedingDev… Please use `configuration` instead init 🙏🏻
