### ISSUE TITLE
@nx-tools/nx-container:init generator fails on latest nx workspace

### ISSUE THREAD

**Issue by gremlin896** [gperdomor/nx-tools#727]
When running `nx g @nx-tools/nx-container:init` I receive the following error: 

```
>  NX  Generating @nx-tools/nx-container:init

 >  NX   Cannot read properties of undefined (reading 'exists')

TypeError: Cannot read properties of undefined (reading 'exists')
    at readNxJson (node_modules/nx/src/generators/utils/project-configuration.js:177:15)
    at _default (node_modules/@nx-tools/nx-container/src/generators/init/generator.js:22:39)
    at Object.<anonymous> (node_modules/nx/src/command-line/generate.js:221:36)
    at Generator.next (<anonymous>)
    at fulfilled (node_modules/tslib/tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I can reproduce this on a fresh nx workspace like so:

1. `npx create-nx-workspace@latest --name=nx-container-test --preset=angular-monorepo --nxCloud=false --appName=someapp --style=css`
2. `npm install @nx-tools/nx-container`
3. `npx nx generate @nx-tools/nx-container:init someapp --verbose --engine=docker --template=react-angular-spa`

The relevant package versions are:
```
"@nrwl/workspace": "15.5.2"
"@nx-tools/nx-container": "4.0.2",
```

**Comment by gperdomor** [comment]
You need to pass the name of the project (--project=appName) to be configured

**Comment by sn0wcat** [comment]
for me it is the same thing - no mather how the command is configured, @nx-tools/nx-container breaks always at the same place, I can't get plugin to run at all.


```bash
yarn nx generate @nx-tools/nx-container:init beeper-api --no-skipFormat --template=nest --no-interactive --dry-run --verbose
yarn run v1.22.19
$ /Users/sn0wcat/beeper/node_modules/.bin/nx generate @nx-tools/nx-container:init beeper-api --no-skipFormat --template=nest --no-interactive --dry-run --verbose

>  NX  Generating @nx-tools/nx-container:init
 >  NX   Cannot read properties of undefined (reading 'exists')
TypeError: Cannot read properties of undefined (reading 'exists')
    at readNxJson (/Users/sn0wcat/beeper/node_modules/nx/src/generators/utils/project-configuration.js:177:15)
    at _default (/Users/sn0wcat/beeper/node_modules/@nx-tools/nx-container/src/generators/init/generator.js:22:39)
    at Object.<anonymous> (/Users/sn0wcat/beeper/node_modules/nx/src/command-line/generate.js:221:36)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/sn0wcat/beeper/node_modules/tslib/tslib.js:115:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

with --project= syntax

```bash
 yarn nx generate @nx-tools/nx-container:init --project=beeper-api --no-skipFormat --template=nest --no-interactive --dry-run --verbose
yarn run v1.22.19
$ /Users/sn0wcat/beeper/node_modules/.bin/nx generate @nx-tools/nx-container:init --project=beeper-api --no-skipFormat --template=nest --no-interactive --dry-run --verbose

>  NX  Generating @nx-tools/nx-container:init


 >  NX   Cannot read properties of undefined (reading 'exists')


TypeError: Cannot read properties of undefined (reading 'exists')
    at readNxJson (/Users/sn0wcat/beeper/node_modules/nx/src/generators/utils/project-configuration.js:177:15)
    at _default (/Users/sn0wcat/beeper/node_modules/@nx-tools/nx-container/src/generators/init/generator.js:22:39)
    at Object.<anonymous> (/Users/sn0wcat/beeper/node_modules/nx/src/command-line/generate.js:221:36)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/sn0wcat/beeper/node_modules/tslib/tslib.js:115:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I am on mac

**Comment by gremlin896** [comment]
As noted by @sn0wcat above, the issue happens regardless of whether `--project` is used or not.

The modified reproduction steps would be:

1. npx create-nx-workspace@latest --name=nx-container-test --preset=angular-monorepo --nxCloud=false --appName=someapp --style=css
2. npm install @nx-tools/nx-container
3. npx nx generate @nx-tools/nx-container:init --project=someapp --verbose --engine=docker --template=react-angular-spa

**Comment by gperdomor** [comment]
Hi everyone, sorry for the inconveniences, can you try with 4.0.3 and let me know

**Comment by steflen-kxl** [comment]
Works 👍  Thanks For Your Fast Support !!

**Comment by gremlin896** [comment]
Thanks, the fix works great!
